# -*- coding: utf-8 -*-
"""ML EXP 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kyf2_uO2p83HN7AWfXfvUWTrCXYhICf6
"""

# FIND-S Algorithm (Google Colab Ready)

# Step 1: Define training data
data = [
    ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', 'Yes'],
    ['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same', 'Yes'],
    ['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change', 'No'],
    ['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change', 'Yes']
]

# Step 2: Initialize hypothesis
hypothesis = ['Ø'] * (len(data[0]) - 1)

print("Initial Hypothesis:", hypothesis)

# Step 3: Apply FIND-S
for i in range(len(data)):
    if data[i][-1] == 'Yes':  # Only positive examples
        for j in range(len(hypothesis)):
            if hypothesis[j] == 'Ø':
                hypothesis[j] = data[i][j]
            elif hypothesis[j] != data[i][j]:
                hypothesis[j] = '?'

    print(f"Step {i+1} Hypothesis:", hypothesis)

# Step 4: Final output
print("\nFinal Hypothesis:", hypothesis)

