# -*- coding: utf-8 -*-
"""exp2 ml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RwVdvwuxFZyDIjD9ukil45Jy7JFUBErT
"""

import csv

def read_csv(filename):
    data = []
    with open(filename, 'r') as file:
        reader = csv.reader(file)
        headers = next(reader)
        for row in reader:
            data.append(row)
    return headers, data

def more_general(h1, h2):
    return all(x == '?' or (x != '0' and (x == y or y == '0'))
               for x, y in zip(h1, h2))

def min_generalizations(h, x):
    new_h = list(h)
    for i in range(len(h)):
        if h[i] == '0':
            new_h[i] = x[i]
        elif h[i] != x[i]:
            new_h[i] = '?'
    return [new_h]

def min_specializations(h, domains, x):
    results = []
    for i in range(len(h)):
        if h[i] == '?':
            for value in domains[i]:
                if value != x[i]:
                    new_h = h.copy()
                    new_h[i] = value
                    results.append(new_h)
        elif h[i] != '0':
            new_h = h.copy()
            new_h[i] = '0'
            results.append(new_h)
    return results

def candidate_elimination(data):
    num_attr = len(data[0]) - 1

    domains = []
    for i in range(num_attr):
        domains.append(list(set(row[i] for row in data)))

    S = [['0'] * num_attr]
    G = [['?'] * num_attr]

    print("Initial Specific Hypothesis:")
    print(S)
    print("Initial General Hypothesis:")
    print(G)

    for row in data:
        x = row[:-1]
        label = row[-1]

        if label.lower() == "yes":
            G = [g for g in G if more_general(g, x)]

            S_new = []
            for s in S:
                if more_general(x, s):
                    S_new.extend(min_generalizations(s, x))
                else:
                    S_new.append(s)

            S = []
            for s in S_new:
                if any(more_general(g, s) for g in G):
                    if s not in S:
                        S.append(s)

        else:
            S = [s for s in S if not more_general(x, s)]

            G_new = []
            for g in G:
                if more_general(g, x):
                    specs = min_specializations(g, domains, x)
                    for h in specs:
                        if any(more_general(h, s) for s in S):
                            if h not in G_new:
                                G_new.append(h)
                else:
                    G_new.append(g)

            G = G_new

        print("\nTraining Example:", row)
        print("Specific Boundary (S):")
        for s in S:
            print(s)
        print("General Boundary (G):")
        for g in G:
            print(g)

    return S, G

# Main
headers, data = read_csv("trainingdata.csv")
S_final, G_final = candidate_elimination(data)

print("\nFinal Specific Boundary:")
print(S_final)

print("\nFinal General Boundary:")
print(G_final)

import pandas as pd

data = [
    ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', 'Yes'],
    ['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same', 'Yes'],
    ['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change', 'No'],
    ['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change', 'Yes']
]

columns = ['Sky', 'AirTemp', 'Humidity', 'Wind', 'Water', 'Forecast', 'EnjoySport']
df = pd.DataFrame(data, columns=columns)
df.to_csv('trainingdata.csv', index=False)

print('trainingdata.csv created successfully:')
print(df)